### ISSUE TITLE
Wrong hyperlink in the "Links Section" on Talk details page

### ISSUE THREAD

**Issue by konarkmodi** [hasgeek/fifthelephant#1]
The Hyperlink in the "links" section on the detail page of a talk is marked wrong.

Example:

http://funnel.hasgeek.com/5el/379-become-a-data-wrangler-learning-how-to-work-with-data

The link in the Links section is :
schoolofdata.org , but the hyperlink set is http://funnel.hasgeek.com/5el/schoolofdata.org which should essentially be http://schoolofdata.org.

**Comment by jace** [comment]
Did you mean to file this bug report against [Funnel](/hasgeek/funnel)? It's known issue -- Funnel doesn't validate the submitted links.

**Comment by jace** [comment]
I've fixed it in Funnel. Links should work properly now. https://github.com/hasgeek/funnel/issues/15
