### ISSUE TITLE
Add Fifth Elephant logo to website

### ISSUE THREAD

**Issue by zainabbawa** [hasgeek/fifthelephant#11]
@rungta @souvikdg please add The Fifth Elephant logo to the site so that it appears in the thumbnail list when I send out information through Facebook.

**Comment by souvikdg** [comment]
@zainabbawa Added. Code has to be deployed before you can start posting.

**Comment by jace** [comment]
I've deployed.

**Comment by souvikdg** [comment]
@zainabbawa [Facebook Debugger](http://developers.facebook.com/tools/debug/og/object?q=fifthelephant.in) says that we should provide a larger logo. Do you have a 1500x1500 version?

**Comment by souvikdg** [comment]
@jace Deploy please.
