### ISSUE TITLE
Networkbar needed

### ISSUE THREAD

**Issue by jace** [hasgeek/fifthelephant#13]
The 2013 website needs the networkbar. Here's the necessary code for `index.html`:

``` jinja
{% from "baseframe/components.html" import networkbar with context -%} {# At top of page #}
{% block networkbar %}{{ networkbar(siteid='events', login=false) }}{% endblock %} {# Where required #}
```

You'll also need the CSS. I'll patch this into an asset you can invoke from the template.

**Comment by souvikdg** [comment]
How do I include CSS, any particular CSS file?

**Comment by jace** [comment]
For anything in the static folder of a theme, use this:

`{{ theme_static('css/foo.css') }}`

You can insert that wherever a path is expected, such as: `<a href="{{…}}">`

**Comment by jace** [comment]
There's also an asset management system that minification and version tagging. To use that:
1. Add the paths to `options/assets_css` and `options/assets_js` in `info.json`.
2. Restart Eventframe so it reads the updated JSON file.
3. Include the assets in your HTML. Look up `eventframe.html` for the invocation. Roughly:

``` jinja
{% assets 'css_all' %}
  <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}
```

Eventframe registers CSS and JS assets under the `css_all` and `js_all` names respectively. It also gives you Bootstrap and the Networkbar CSS as part of `css_all`.

**Comment by souvikdg** [comment]
@jace I meant — Which css file do I have to include for the networkbar?

**Comment by jace** [comment]
It's not available as an independent asset. I'll fix that. However, you can directly link to `/_baseframe/css/networkbar.css`.

**Comment by souvikdg** [comment]
Is there a dark theme?

**Comment by jace** [comment]
Yes. As seen on [hacknight.in](http://hacknight.in/):

``` jinja
{{ networkbar(siteid='events', login=false, baseclass='hg-dark') }}
```

The dark theme uses transparency and converts to 100% black on hover.

We'll switch `login` over to `true` when we add features that require a user to login.

**Comment by souvikdg** [comment]
Done!
