### ISSUE TITLE
Blog missing in navigation

### ISSUE THREAD

**Issue by jace** [hasgeek/fifthelephant#14]
The Fifth Elephant blog is missing from the 2013 site navigation. This makes it hard to discover the blog and to return to it after clicking away.

![Navigation bar](https://f.cloud.github.com/assets/26695/522250/cc4372ea-c011-11e2-8320-9ebbbc0dabf4.png)

**Comment by souvikdg** [comment]
Though a compromise, I felt it was acceptable. The blogposts (as announcements) are prominently placed on the homepage and further the blog is linked from the footer on every page. Adding another link there will make it crowded in lower widths.

**Comment by jace** [comment]
Accepted.
