### ISSUE TITLE
Top links are broken when I scroll up from the middle of the page

### ISSUE THREAD

**Issue by jaseemabid** [hasgeek/fifthelephant#18]
![latest-screenshot](https://f.cloud.github.com/assets/601714/594523/2d11e474-ca91-11e2-9985-4070e4ad116f.png)

**Comment by jace** [comment]
What browser/OS is that? I've been working in Chrome/Mac and it renders fine in that. Also could be a cache/fonts issue. @souvikdg

**Comment by jaseemabid** [comment]
I remember a  decent website which used to show all browser info but its gone now :(

Latest chrome on linux. 1366px wide screen. JS on, no flash. Enough?

**Comment by jace** [comment]
I don't have that setup at hand to test with, so can you check what is causing so much spacing to appear? Is there something in the stylesheet we haven't noticed?

@souvikdg is the site's designer, but not sure he's around today.

**Comment by souvikdg** [comment]
@jace Opened http://fifthelephant.in in the latest Chrome running in Ubuntu VM. Couldn’t replicate the issue.

**Comment by jaseemabid** [comment]
25 and 50% width for 'sub-group' is breaking things for me and adding a new line.  Sorry for the ugly patch, but this fixes it for me. 

```
group {
    width: 25%;   -> width: 24%;
}

group.conference {
    width: 50%;  -> width: 47%;
}
```

Sometimes browsers act as if 25 \* 4 = 102 and add a new line :(

**Comment by jaseemabid** [comment]
![latest-screenshot](https://f.cloud.github.com/assets/601714/605551/13953980-cd19-11e2-8b8f-f862163e45bf.png)

**Comment by souvikdg** [comment]
@jace If rounding off/percentage calculation is really the issue c8fa48f49353655e03ede99f05e7369e580c6fcf works around that.

**Comment by jace** [comment]
@jaseemabid Deployed latest update. Is it fixed now?

**Comment by jaseemabid** [comment]
Yup! Looks good. 

![latest-screenshot](https://f.cloud.github.com/assets/601714/611333/3411fc28-cdcf-11e2-9da6-c65b1dc1062f.png)
