### ISSUE TITLE
Remove links from team photos

### ISSUE THREAD

**Issue by zainabbawa** [hasgeek/fifthelephant#19]
Remove links from each of the photos of team members. We have not finished profiles project yet. Clicking on links takes me to the top of the home page.

**Comment by souvikdg** [comment]
Link to twitter / linked-in (or any other online profile)?

**Comment by zainabbawa** [comment]
Except for Radha, everyone else has either twitter or LinkedIn profiles. Nimisha has a Facebook profile.

**Comment by souvikdg** [comment]
Removed links.

@jace Deploy please.
