### ISSUE TITLE
Please don't use the name sponsor in a class

### ISSUE THREAD

**Issue by nigelbabu** [hasgeek/fifthelephant#2]
Using the name 'sponsor' for a class makes adblock not display it.  I'm pretty sure a large group of people use Adblock and none of them will the see the sponsor listings.

**Comment by jace** [comment]
Strange, because I use Adblock and I'm not affected. No special rules for fifthelephant.in.

**Comment by ashwan** [comment]
I found this: http://leonpaternoster.com/2011/02/adblockers-ids-and-class-names/

I guess it might be upto the list people have installed.

**Comment by nigelbabu** [comment]
Ah, that could do it. I've had other people with Adblock Plus tell me that divs with classname sponsor are hidden automatically. I think we should stay on the safe side and name it hsponsor or something.

**Comment by miteshashar** [comment]
Stale.
