### ISSUE TITLE
Pune event: Incorrect link for Hasgeek Logo

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/fifthelephant#21]
On Pune event page, in the Sponsors section, the HasGeek logo points to the Thoughtworks website.

**Comment by hallidude** [comment]
Looks all right to me.

**Comment by miteshashar** [comment]
It does show the correct one to me now.
It somehow was showing the incorrect link when I checked. I also reloaded the page and checked the html source before posting the issue. :D
