### ISSUE TITLE
Add image and description for Facebook in meta tags

### ISSUE THREAD

**Issue by ashwan** [hasgeek/fifthelephant#3]
Sharing the fifthelephant.in page on Facebook only brings up sponsor logos as a possible thumbnail and no description.

For the description, we need to put something in the meta description tag which is blank now and for the thumbnail, we need the following,

<pre>&lt;link rel=”image_src” href=”thumbnail_image” /&gt;</pre>

I think we should use the four elephants sitting together as the thumbnail image, I really like that one! :)

**Comment by jace** [comment]
Ashwan, the description should be automatically pulled from /2012/(index)'s Summary field. Can you confirm it has text?

For the image, add the tag to a `{block pageheaders}` in `layout.html`, below the title block.

**Comment by jace** [comment]
That's `{% block pageheaders %}`.

**Comment by miteshashar** [comment]
Stale.
