### ISSUE TITLE
Updated text about The Fifth Elephant 2012

### ISSUE THREAD

**Issue by zainabbawa** [hasgeek/fifthelephant#8]
@souvikdg please see the new txt file titled "About the Fifth Elephant 2012" for the updating text currently highlighted in the section about 2012 edition.

**Comment by rungta** [comment]
@zainabbawa I’ve updated the website with the content, but it’ll be nice if that text is linked to actual sessions in sentences such as these:

> They learnt about programming languages and libraries available for producing compelling visualizations. In the analytics track, statisticians and analysts spoke about various tools and techniques for building business intelligence and telling stories with data.

Not a high-priority requirement though.

**Comment by zainabbawa** [comment]
@rungta Your comment makes perfect sense. I don't know how to add links to the text in GitHub. Sent you an email. Will learn a little more about GitHub in the next few days :)

**Comment by souvikdg** [comment]
Links have been added. Closing this issue.
